# AWS CodeDeploy recipe
version: 0.1
os: linux 
files:
  - source: /
    destination: /var/www/cart
hooks:
  ApplicationStop:
    - location: /var/www/cart/node_modules/forever/bin/forever stop 0
      runas: ec2-user
  AfterInstall:
    - location: /usr/local/bin/npm install    
      runas: ec2-user
  ApplicationStart:
    - location: /var/www/cart/node_modules/forever/bin/forever server.js
      runas: ec2-user