# AWS CodeDeploy recipe
version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/cart
permissions:
  - object: /var/www/cart
    pattern: "**"
hooks:
  ApplicationStop:
    - location: deploy_hooks/shutdown.sh
  AfterInstall:
    - location: deploy_hooks/npmInstall.sh
  ApplicationStart:
    - location: deploy_hooks/start.sh